create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null default '',
  class_name text not null default '',
  date text not null check (date in ('30일(토)', '31일(일)')),
  phone text not null,
  created_at timestamptz not null default now()
);

create index if not exists participants_date_idx on public.participants (date);
create index if not exists participants_name_idx on public.participants (name);
create index if not exists participants_phone_idx on public.participants (phone);

grant select, insert, update, delete on public.participants to service_role;
